# Generated by Django 2.2.5 on 2019-12-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageStepGuideTable',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('BgImg', models.ImageField(upload_to='CMS/About US Image/')),
                ('Heading1', models.TextField()),
                ('Heading1Content', models.TextField()),
                ('Heading2', models.TextField()),
                ('Heading2Content', models.TextField()),
                ('Heading3', models.TextField()),
                ('Heading3Content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ABOUTUSCMS',
            fields=[
                ('about_us_uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('AboutHeading', models.TextField()),
                ('AboutArcturusContent', models.TextField()),
                ('AboutUSImage', models.ImageField(upload_to='CMS/About US Image/')),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfileData',
            fields=[
                ('img', models.ImageField(upload_to='Admin Profile Image/')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('dob', models.TextField()),
                ('contact', models.TextField()),
                ('address', models.TextField()),
                ('education', models.TextField()),
                ('skills', models.TextField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('uni_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminToDoListTable',
            fields=[
                ('TaskNo', models.TextField(primary_key=True, serialize=False)),
                ('TaskDesc', models.TextField()),
                ('CreatedAt', models.DateTimeField()),
                ('DeadLineAt', models.DateTimeField()),
                ('SpecialNote', models.TextField()),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='common_field_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_banner_heading', models.CharField(blank=True, max_length=2048)),
                ('top_banner_content', models.CharField(blank=True, max_length=2048)),
                ('footer_acturus_desc', models.CharField(blank=True, max_length=2048)),
                ('footer_acturus_address', models.CharField(blank=True, max_length=2048)),
                ('footer_acturus_contact', models.CharField(blank=True, max_length=2048)),
                ('footer_acturus_email', models.CharField(blank=True, max_length=2048)),
                ('footer_latest_news_content_1', models.CharField(blank=True, max_length=2048)),
                ('footer_latest_news_pic_1', models.ImageField(blank=True, upload_to='AdminApp/homepage/news/')),
                ('footer_latest_news_content_2', models.CharField(blank=True, max_length=2048)),
                ('footer_latest_news_pic_2', models.ImageField(blank=True, upload_to='AdminApp/homepage/news/')),
                ('footer_latest_news_content_3', models.CharField(blank=True, max_length=2048)),
                ('footer_latest_news_pic_3', models.ImageField(blank=True, upload_to='AdminApp/homepage/news/')),
            ],
        ),
        migrations.CreateModel(
            name='CopyRightCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=1, serialize=False)),
                ('copyRightData', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DEVELOPMENTROADMAPCMS',
            fields=[
                ('road_map_uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('Heading1EditMonth', models.TextField()),
                ('Heading1EditLabel', models.TextField()),
                ('Heading2EditMonth', models.TextField()),
                ('Heading2EditLabel', models.TextField()),
                ('Heading3EditMonth', models.TextField()),
                ('Heading3EditLabel', models.TextField()),
                ('Heading4EditMonth', models.TextField()),
                ('Heading4EditLabel', models.TextField()),
                ('Heading5EditMonth', models.TextField()),
                ('Heading5EditLabel', models.TextField()),
                ('Heading6EditMonth', models.TextField()),
                ('Heading6EditLabel', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='edit_about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(blank=True, max_length=2048)),
                ('about_body', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='edit_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_feedback_review', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='edit_fooding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fooding_heading', models.CharField(blank=True, max_length=2048)),
                ('fooding_body', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='edit_hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_heading', models.CharField(blank=True, max_length=2048)),
                ('content_body', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='edit_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_heading', models.CharField(blank=True, max_length=2048)),
                ('payment_body', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='edit_recreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recreation_heading', models.CharField(blank=True, max_length=2048)),
                ('recreation_body', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='edit_tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_heading', models.CharField(blank=True, max_length=2048)),
                ('tour_body', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='edit_travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_heading', models.CharField(blank=True, max_length=2048)),
                ('travel_body', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='edit_white_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_page_heading', models.CharField(blank=True, max_length=2048)),
                ('white_page_body', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='FoodingContentTableCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FooterCMS',
            fields=[
                ('footer_uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('FooterContent', models.TextField()),
                ('FooterAddress', models.TextField()),
                ('FooterPhone', models.TextField()),
                ('FooterMail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeaderCMS',
            fields=[
                ('header_uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('HeaderHeading', models.TextField()),
                ('HeaderHeadingContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_services', models.TextField(blank=True, default='our services here', max_length=1024)),
                ('services_pic_1', models.ImageField(blank=True, upload_to='AdminApp/homepage/service/')),
                ('services_pic_2', models.ImageField(blank=True, upload_to='AdminApp/homepage/service/')),
                ('services_pic_3', models.ImageField(blank=True, upload_to='AdminApp/homepage/service/')),
                ('services_pic_4', models.ImageField(blank=True, upload_to='AdminApp/homepage/service/')),
                ('services_pic_5', models.ImageField(blank=True, upload_to='AdminApp/homepage/service/')),
                ('services_pic_6', models.ImageField(blank=True, upload_to='AdminApp/homepage/service/')),
                ('calculate_live_cryptocurrency_content', models.TextField(blank=True, default='description of live cryptocurrency calculator', max_length=512)),
                ('feedback_background_pic', models.ImageField(blank=True, upload_to='AdminApp/homepage/feedback/')),
                ('about_us_content', models.TextField(blank=True, max_length=2048)),
                ('about_cryptocurrency', models.ImageField(blank=True, upload_to='AdminApp/homepage/about_crypto/')),
                ('why_choose_us_content', models.TextField(blank=True, max_length=2048)),
                ('why_choose_us_pic', models.ImageField(blank=True, upload_to='AdminApp/homepage/why_choose_us/')),
                ('choose_us_point_1', models.CharField(blank=True, max_length=2048)),
                ('choose_us_point_2', models.CharField(blank=True, max_length=2048)),
                ('choose_us_point_3', models.CharField(blank=True, max_length=2048)),
                ('choose_us_point_4', models.CharField(blank=True, max_length=2048)),
                ('footer_acturus_desc', models.CharField(default='some Arcturus description', max_length=256)),
                ('footer_acturus_address', models.CharField(default='Street,City,Country', max_length=64)),
                ('footer_acturus_contact', models.CharField(default='(+91) 987 654 3210', max_length=20)),
                ('footer_acturus_email', models.CharField(default='office@example.com', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='HotelContentTableCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LatestNewsCMS',
            fields=[
                ('news_uni_key', models.SmallIntegerField(primary_key=1, serialize=False)),
                ('LatestNewsImg1', models.ImageField(upload_to='CMS/Latest News/')),
                ('LatestNewsContent1', models.TextField()),
                ('LatestNewsDate1', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationForNewUserRegistration',
            fields=[
                ('Noti_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Noti_msg', models.TextField()),
                ('Noti_time', models.DateTimeField()),
                ('check', models.BooleanField()),
                ('New_User_Mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OurSerice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OURSERVICECMS1',
            fields=[
                ('service_uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('OurSericeContent', models.TextField()),
                ('OurSericeImg1', models.ImageField(upload_to='CMS/OUR Service Image/')),
                ('OurSericeImg2', models.ImageField(upload_to='CMS/OUR Service Image/')),
                ('OurSericeImg3', models.ImageField(upload_to='CMS/OUR Service Image/')),
                ('OurSericeImg4', models.ImageField(upload_to='CMS/OUR Service Image/')),
                ('OurSericeImg5', models.ImageField(upload_to='CMS/OUR Service Image/')),
                ('OurSericeImg6', models.ImageField(upload_to='CMS/OUR Service Image/')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsContentTableCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PolicyCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('Data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecreationContentTableCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewBackgroundCMS1',
            fields=[
                ('review_bg_uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('OurSericeImg1', models.ImageField(upload_to='CMS/Review BackGround Image/')),
            ],
        ),
        migrations.CreateModel(
            name='road_map_edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_roadmap_content', models.TextField(blank=True)),
                ('development_roadmap_phase_1', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_content_1', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_image_1', models.ImageField(blank=True, upload_to='AdminApp/homepage/roadmap/')),
                ('development_roadmap_phase_2', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_content_2', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_image_2', models.ImageField(blank=True, upload_to='AdminApp/homepage/roadmap/')),
                ('development_roadmap_phase_3', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_content_3', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_image_3', models.ImageField(blank=True, upload_to='AdminApp/homepage/roadmap/')),
                ('development_roadmap_phase_4', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_content_4', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_image_4', models.ImageField(blank=True, upload_to='AdminApp/homepage/roadmap/')),
                ('development_roadmap_phase_5', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_content_5', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_image_5', models.ImageField(blank=True, upload_to='AdminApp/homepage/roadmap/')),
                ('development_roadmap_phase_6', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_content_6', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_image_6', models.ImageField(blank=True, upload_to='AdminApp/homepage/roadmap/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedialCMS',
            fields=[
                ('social_uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('facebook_link', models.TextField()),
                ('twitter_link', models.TextField()),
                ('googleplus', models.TextField()),
                ('linkedin', models.TextField()),
                ('youtube', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.TextField(blank=True)),
                ('twitter_link', models.TextField(blank=True)),
                ('googleplus', models.TextField(blank=True)),
                ('linkedin', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditionCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('Data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ToursContentTableCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelsContentTableCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WhitePaperCMS',
            fields=[
                ('white_uni_key', models.SmallIntegerField(primary_key=1, serialize=False)),
                ('mainhead', models.TextField()),
                ('Headsub1', models.TextField()),
                ('Headsub1Content', models.TextField()),
                ('Headsub2', models.TextField()),
                ('Headsub2Content', models.TextField()),
                ('Headsub3', models.TextField()),
                ('Headsub3Content', models.TextField()),
                ('Headsub4', models.TextField()),
                ('Headsub4Content', models.TextField()),
                ('Headsub5', models.TextField()),
                ('Headsub5Content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WhitePaperPDFCMS',
            fields=[
                ('pdf_uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('pdffile', models.FileField(upload_to='CMS/White Paper PDF/')),
            ],
        ),
        migrations.CreateModel(
            name='WHYCHOOSEUSCMS',
            fields=[
                ('why_coose_us_uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('ChooseUSImage', models.ImageField(upload_to='CMS/Choose US Image/')),
                ('ChooseUsHeading1', models.TextField()),
                ('ChooseUsHeading1Content', models.TextField()),
                ('ChooseUsHeading2', models.TextField()),
                ('ChooseUsHeading2Content', models.TextField()),
                ('ChooseUsHeading3', models.TextField()),
                ('ChooseUsHeading3Content', models.TextField()),
                ('ChooseUsHeading4', models.TextField()),
                ('ChooseUsHeading4Content', models.TextField()),
            ],
        ),
    ]
