# Generated by Django 2.2.5 on 2019-10-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='common_field_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_banner_heading', models.CharField(blank=True, max_length=2048)),
                ('top_banner_content', models.CharField(blank=True, max_length=2048)),
                ('footer_acturus_desc', models.CharField(blank=True, max_length=2048)),
                ('footer_acturus_address', models.CharField(blank=True, max_length=2048)),
                ('footer_acturus_contact', models.CharField(blank=True, max_length=2048)),
                ('footer_acturus_email', models.CharField(blank=True, max_length=2048)),
                ('footer_latest_news_content_1', models.CharField(blank=True, max_length=2048)),
                ('footer_latest_news_pic_1', models.ImageField(blank=True, upload_to='AdminApp/homepage/news/')),
                ('footer_latest_news_content_2', models.CharField(blank=True, max_length=2048)),
                ('footer_latest_news_pic_2', models.ImageField(blank=True, upload_to='AdminApp/homepage/news/')),
                ('footer_latest_news_content_3', models.CharField(blank=True, max_length=2048)),
                ('footer_latest_news_pic_3', models.ImageField(blank=True, upload_to='AdminApp/homepage/news/')),
            ],
        ),
        migrations.CreateModel(
            name='edit_about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(blank=True, max_length=2048)),
                ('about_body', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='edit_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_feedback_review', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='edit_fooding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fooding_heading', models.CharField(blank=True, max_length=2048)),
                ('fooding_body', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='edit_hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_heading', models.CharField(blank=True, max_length=2048)),
                ('content_body', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='edit_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_heading', models.CharField(blank=True, max_length=2048)),
                ('payment_body', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='edit_recreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recreation_heading', models.CharField(blank=True, max_length=2048)),
                ('recreation_body', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='edit_tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_heading', models.CharField(blank=True, max_length=2048)),
                ('tour_body', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='edit_travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_heading', models.CharField(blank=True, max_length=2048)),
                ('travel_body', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='edit_white_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_page_heading', models.CharField(blank=True, max_length=2048)),
                ('white_page_body', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_services', models.TextField(blank=True, default='our services here', max_length=1024)),
                ('services_pic_1', models.ImageField(blank=True, upload_to='AdminApp/homepage/service/')),
                ('services_pic_2', models.ImageField(blank=True, upload_to='AdminApp/homepage/service/')),
                ('services_pic_3', models.ImageField(blank=True, upload_to='AdminApp/homepage/service/')),
                ('services_pic_4', models.ImageField(blank=True, upload_to='AdminApp/homepage/service/')),
                ('services_pic_5', models.ImageField(blank=True, upload_to='AdminApp/homepage/service/')),
                ('services_pic_6', models.ImageField(blank=True, upload_to='AdminApp/homepage/service/')),
                ('calculate_live_cryptocurrency_content', models.TextField(blank=True, default='description of live cryptocurrency calculator', max_length=512)),
                ('feedback_background_pic', models.ImageField(blank=True, upload_to='AdminApp/homepage/feedback/')),
                ('about_us_content', models.TextField(blank=True, max_length=2048)),
                ('about_cryptocurrency', models.ImageField(blank=True, upload_to='AdminApp/homepage/about_crypto/')),
                ('why_choose_us_content', models.TextField(blank=True, max_length=2048)),
                ('why_choose_us_pic', models.ImageField(blank=True, upload_to='AdminApp/homepage/why_choose_us/')),
                ('choose_us_point_1', models.CharField(blank=True, max_length=2048)),
                ('choose_us_point_2', models.CharField(blank=True, max_length=2048)),
                ('choose_us_point_3', models.CharField(blank=True, max_length=2048)),
                ('choose_us_point_4', models.CharField(blank=True, max_length=2048)),
                ('footer_acturus_desc', models.CharField(default='some Arcturus description', max_length=256)),
                ('footer_acturus_address', models.CharField(default='Street,City,Country', max_length=64)),
                ('footer_acturus_contact', models.CharField(default='(+91) 987 654 3210', max_length=20)),
                ('footer_acturus_email', models.CharField(default='office@example.com', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OurSerice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='road_map_edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_roadmap_content', models.TextField(blank=True)),
                ('development_roadmap_phase_1', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_content_1', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_image_1', models.ImageField(blank=True, upload_to='AdminApp/homepage/roadmap/')),
                ('development_roadmap_phase_2', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_content_2', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_image_2', models.ImageField(blank=True, upload_to='AdminApp/homepage/roadmap/')),
                ('development_roadmap_phase_3', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_content_3', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_image_3', models.ImageField(blank=True, upload_to='AdminApp/homepage/roadmap/')),
                ('development_roadmap_phase_4', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_content_4', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_image_4', models.ImageField(blank=True, upload_to='AdminApp/homepage/roadmap/')),
                ('development_roadmap_phase_5', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_content_5', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_image_5', models.ImageField(blank=True, upload_to='AdminApp/homepage/roadmap/')),
                ('development_roadmap_phase_6', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_content_6', models.CharField(blank=True, max_length=2048)),
                ('development_roadmap_image_6', models.ImageField(blank=True, upload_to='AdminApp/homepage/roadmap/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.TextField(blank=True)),
                ('twitter_link', models.TextField(blank=True)),
                ('googleplus', models.TextField(blank=True)),
                ('linkedin', models.TextField(blank=True)),
            ],
        ),
    ]
