# Generated by Django 2.2.5 on 2019-10-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABOUTUSCMS',
            fields=[
                ('about_us_uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('AboutHeading', models.TextField()),
                ('AboutArcturusContent', models.TextField()),
                ('AboutUSImage', models.ImageField(upload_to='CMS/About US Image/')),
            ],
        ),
    ]
