# Generated by Django 2.2.5 on 2019-10-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_aboutuscms'),
    ]

    operations = [
        migrations.CreateModel(
            name='WHYCHOOSEUSCMS',
            fields=[
                ('why_coose_us_uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('ChooseUSImage', models.ImageField(upload_to='CMS/Choose US Image/')),
                ('ChooseUsHeading1', models.TextField()),
                ('ChooseUsHeading1Content', models.TextField()),
                ('ChooseUsHeading2', models.TextField()),
                ('ChooseUsHeading2Content', models.TextField()),
                ('ChooseUsHeading3', models.TextField()),
                ('ChooseUsHeading3Content', models.TextField()),
                ('ChooseUsHeading4', models.TextField()),
                ('ChooseUsHeading4Content', models.TextField()),
            ],
        ),
    ]
