# Generated by Django 2.2.5 on 2019-11-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_socialmedialcms_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialcms',
            name='youtube',
            field=models.TextField(null=True),
        ),
    ]
