# Generated by Django 2.2.5 on 2019-10-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_developmentroadmapcms'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderCMS',
            fields=[
                ('header_uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('HeaderHeading', models.TextField()),
                ('HeaderHeadingContent', models.TextField()),
            ],
        ),
    ]
