# Generated by Django 2.2.5 on 2019-10-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_headercms'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterCMS',
            fields=[
                ('footer_uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('FooterContent', models.TextField()),
                ('FooterAddress', models.TextField()),
                ('FooterPhone', models.TextField()),
                ('FooterMail', models.TextField()),
            ],
        ),
    ]
