# Generated by Django 2.2.5 on 2019-10-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_footercms'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageStepGuideTable',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('BgImg', models.ImageField(upload_to='CMS/About US Image/')),
                ('Heading1', models.TextField()),
                ('Heading1Content', models.TextField()),
                ('Heading2', models.TextField()),
                ('Heading2Content', models.TextField()),
                ('Heading3', models.TextField()),
                ('Heading3Content', models.TextField()),
            ],
        ),
    ]
