# Generated by Django 2.2.5 on 2019-10-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_aboutpagestepguidetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitePaperCMS',
            fields=[
                ('white_uni_key', models.SmallIntegerField(primary_key=1, serialize=False)),
                ('mainhead', models.TextField()),
                ('Headsub1', models.TextField()),
                ('Headsub1Content', models.TextField()),
                ('Headsub2', models.TextField()),
                ('Headsub2Content', models.TextField()),
                ('Headsub3', models.TextField()),
                ('Headsub3Content', models.TextField()),
                ('Headsub4', models.TextField()),
                ('Headsub4Content', models.TextField()),
                ('Headsub5', models.TextField()),
                ('Headsub5Content', models.TextField()),
            ],
        ),
    ]
