# Generated by Django 2.2.5 on 2019-10-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_whitepapercms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyRightCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=1, serialize=False)),
                ('copyRightData', models.TextField()),
            ],
        ),
    ]
