# Generated by Django 2.2.5 on 2019-10-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_latestnewscms'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitePaperPDFCMS',
            fields=[
                ('pdf_uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('pdffile', models.FileField(upload_to='CMS/White Paper PDF/')),
            ],
        ),
    ]
