# Generated by Django 2.2.5 on 2019-10-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_whitepaperpdfcms'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedialCMS',
            fields=[
                ('social_uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('facebook_link', models.TextField()),
                ('twitter_link', models.TextField()),
                ('googleplus', models.TextField()),
                ('linkedin', models.TextField()),
            ],
        ),
    ]
