# Generated by Django 2.2.5 on 2019-10-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_socialmedialcms'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfileData',
            fields=[
                ('img', models.ImageField(upload_to='Admin Profile Image/')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('dob', models.TextField()),
                ('contact', models.TextField()),
                ('address', models.TextField()),
                ('education', models.TextField()),
                ('skills', models.TextField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('uni_key', models.TextField()),
            ],
        ),
    ]
