# Generated by Django 2.2.5 on 2019-10-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0013_adminprofiledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminToDoListTable',
            fields=[
                ('TaskNo', models.TextField(primary_key=True, serialize=False)),
                ('TaskDesc', models.TextField()),
                ('CreatedAt', models.DateTimeField()),
                ('DeadLineAt', models.DateTimeField()),
                ('SpecialNote', models.TextField()),
                ('Status', models.BooleanField()),
            ],
        ),
    ]
