# Generated by Django 2.2.5 on 2019-10-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0014_admintodolisttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('Data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditionCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('Data', models.TextField()),
            ],
        ),
    ]
