# Generated by Django 2.2.5 on 2019-10-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0015_policycms_termsandconditioncms'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationForNewUserRegistration',
            fields=[
                ('Noti_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Noti_msg', models.TextField()),
                ('Noti_time', models.DateTimeField()),
                ('check', models.BooleanField()),
                ('New_User_Mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
