# Generated by Django 2.2.5 on 2019-11-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0016_notificationfornewuserregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodingContentTableCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelContentTableCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsContentTableCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecreationContentTableCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ToursContentTableCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelsContentTableCMS',
            fields=[
                ('uni_key', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
    ]
