# Generated by Django 2.2.5 on 2019-12-06 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20191206_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetail',
            name='otp',
            field=models.FloatField(default=909),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 11, 23, 35, 53067)),
        ),
    ]
