# Generated by Django 2.2.5 on 2019-10-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWhitePaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_pdf', models.FileField(upload_to='WhitePaperFolder')),
            ],
        ),
    ]
