# Generated by Django 2.2.5 on 2019-10-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileData',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('mdName', models.TextField()),
                ('phone', models.TextField()),
                ('fax', models.TextField()),
                ('country', models.TextField()),
                ('state_name', models.TextField()),
                ('zipcode', models.TextField()),
            ],
        ),
    ]
