# Generated by Django 2.2.5 on 2019-10-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedbacktable',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='user_mail',
            field=models.EmailField(max_length=254),
        ),
    ]
