# Generated by Django 2.2.5 on 2019-10-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_userprofiledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinrequest',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
