# Generated by Django 2.2.5 on 2019-12-09 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20191209_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 16, 55, 37, 795643)),
        ),
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='UserImg',
            field=models.ImageField(default='https://www.elegantthemes.com/blog/wp-content/uploads/2017/01/shutterstock_534491617-600.jpg', upload_to='Review User Image/'),
        ),
    ]
