# Generated by Django 2.2.5 on 2019-11-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_userprofileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedbacktable',
            name='UserImg',
            field=models.ImageField(default='http://127.0.0.1:8000/media/User%20Profile%20Image/user4-128x128.jpg', upload_to='Review User Image/'),
        ),
    ]
