# Generated by Django 2.2.5 on 2019-11-29 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_auto_20191129_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 18, 14, 43, 418164)),
        ),
    ]
