# Generated by Django 2.2.5 on 2019-12-13 11:51

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_auto_20191213_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinrequest',
            name='tomail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='coinrequest',
            name='withdraw_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 17, 21, 15, 560275)),
        ),
    ]
