# Generated by Django 2.2.5 on 2019-11-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_userfeedbacktable_userimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='UserImg',
            field=models.ImageField(default='/media/User%20Profile%20Image/user4-128x128.jpg', upload_to='Review User Image/'),
        ),
    ]
