# Generated by Django 2.2.5 on 2019-11-02 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_auto_20191102_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 16, 53, 49, 996232)),
        ),
    ]
