# Generated by Django 2.2.5 on 2019-12-19 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_auto_20191213_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinrequest',
            name='transferout',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coinrequest',
            name='trnsferin',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 14, 50, 41, 598885)),
        ),
    ]
