# Generated by Django 2.2.5 on 2019-12-19 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_auto_20191219_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinrequest',
            name='trnsferin',
        ),
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 14, 55, 40, 7181)),
        ),
    ]
