# Generated by Django 2.2.5 on 2019-12-02 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_auto_20191202_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 16, 28, 59, 140991)),
        ),
    ]
