# Generated by Django 2.2.5 on 2019-12-02 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_auto_20191202_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 2, 16, 29, 7, 510546)),
        ),
    ]
