# Generated by Django 2.2.5 on 2019-12-03 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_auto_20191202_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 11, 3, 34, 131259)),
        ),
    ]
