# Generated by Django 2.2.5 on 2019-12-24 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_auto_20191219_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 24, 11, 27, 40, 781074)),
        ),
    ]
