# Generated by Django 2.2.5 on 2019-12-03 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_auto_20191203_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinrequest',
            name='direct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coinrequest',
            name='refere',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 11, 34, 42, 225171)),
        ),
    ]
