# Generated by Django 2.2.5 on 2019-12-03 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_auto_20191203_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinrequest',
            name='direct',
        ),
        migrations.RemoveField(
            model_name='coinrequest',
            name='refere',
        ),
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 11, 36, 49, 847440)),
        ),
    ]
