# Generated by Django 2.2.5 on 2019-12-03 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_auto_20191203_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 12, 43, 21, 418601)),
        ),
    ]
