# Generated by Django 2.2.5 on 2019-12-03 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_auto_20191203_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallettablehistory',
            name='direct',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 16, 30, 1, 87934)),
        ),
    ]
