# Generated by Django 2.2.5 on 2019-12-04 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0016_auto_20191203_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountcoin',
            name='refercoin',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coinrequest',
            name='direct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coinrequest',
            name='refere',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccountcoin',
            name='no_of_coin',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 16, 2, 15, 426382)),
        ),
    ]
