# Generated by Django 2.2.5 on 2019-12-04 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_auto_20191204_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 16, 2, 31, 628916)),
        ),
    ]
