# Generated by Django 2.2.5 on 2019-12-05 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0018_auto_20191204_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetail',
            name='otp',
            field=models.FloatField(default=696),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 12, 3, 28, 725063)),
        ),
    ]
