# Generated by Django 2.2.5 on 2019-12-05 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0020_auto_20191205_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 12, 53, 34, 15720)),
        ),
    ]
