# Generated by Django 2.2.5 on 2019-12-05 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0021_auto_20191205_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinrequest',
            name='transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 15, 7, 58, 206414)),
        ),
    ]
