# Generated by Django 2.2.5 on 2019-12-05 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0022_auto_20191205_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinrequest',
            name='source',
            field=models.CharField(default='money', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 15, 31, 30, 294737)),
        ),
    ]
