# Generated by Django 2.2.5 on 2019-12-05 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0023_auto_20191205_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 15, 38, 43, 276247)),
        ),
    ]
