# Generated by Django 2.2.5 on 2019-12-05 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0025_auto_20191205_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedbacktable',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 17, 57, 24, 724576)),
        ),
    ]
